#!/bin/bash
#set -e
##################################################################################################################
# Author    : Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website   : https://www.ariser.eu
# Website   : https://www.arcolinux.info
# Website   : https://www.arcolinux.com
# Website   : https://www.arcolinuxd.com
# Website   : https://www.arcolinuxb.com
# Website   : https://www.arcolinuxiso.com
# Website   : https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue

#end colors
#tput sgr0
##################################################################################################################

package_list=(
    "catfish"
    "xfce4"
    "xfce4-goodies"
    "arcolinux-xfce-prime-git"
    "arcolinux-faces-git"
)

# Initialize an empty array for packages that are actually installed
installed_packages=()

# Check each package if it's installed
for pkg in "${package_list[@]}"; do
    if pacman -Q "$pkg" &> /dev/null; then
        installed_packages+=("$pkg")
    else
        echo "$pkg is not installed."
    fi
done

# If there are any installed packages, remove them
if [ ${#installed_packages[@]} -ne 0 ]; then
    echo "Removing installed packages..."
    pacman -Rns --noconfirm "${installed_packages[@]}"
else
    echo "No packages from the list are installed."
fi
